version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: linktic-postgres
    environment:
      POSTGRES_USER: linktic
      POSTGRES_PASSWORD: password
      POSTGRES_DB: linktic_db # fallback, we use init script for specifics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  # Minimal observability setup (Optional based on requirements but good for "Senior" points)
  # zipkin:
  #   image: openzipkin/zipkin
  #   ports:
  #     - "9411:9411"

volumes:
  postgres_data:
